// Embeds the Kinan brand assets as data in lib/brand-logo.ts, so the app, the single-file demo, the report viewer and
// the slide player all show them without extra files or network:
//   brand/kinan-logo.svg | .png | .webp | .jpg  → KINAN_LOGO (data URI) and, for an SVG, KINAN_LOGO_PATH + viewBox so the
//                                                 logo can be drawn inline in any colour (charcoal on light, white on dark)
//   brand/kinan-chevron.svg                      → KINAN_CHEVRON_PATH + viewBox (the orange "›" glyph)
//   brand/kinan-texture.jpg | .png | .webp       → KINAN_TEXTURE (the faceted light-grey page texture)
// No logo file → KINAN_LOGO = null and the typographic lockup is shown instead. Run: npm run brand (also before builds).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const TYPES = { svg: "image/svg+xml", png: "image/png", webp: "image/webp", jpg: "image/jpeg", jpeg: "image/jpeg" };
const find = (base, exts) => exts.map((ext) => path.join(root, "brand", `${base}.${ext}`)).find(existsSync);
const uri = (file) => (file ? `data:${TYPES[path.extname(file).slice(1)]};base64,${readFileSync(file).toString("base64")}` : null);
const svgParts = (file) => {
  if (!file || !file.endsWith(".svg")) return { path: null, viewBox: null };
  const s = readFileSync(file, "utf8");
  const vb = s.match(/viewBox="([^"]+)"/)?.[1] ?? null, d = s.match(/<path[^>]*\sd="([^"]+)"/)?.[1] ?? null;
  return { path: d, viewBox: vb };
};
const logo = find("kinan-logo", Object.keys(TYPES)), chev = find("kinan-chevron", ["svg"]), tex = find("kinan-texture", ["jpg", "jpeg", "png", "webp"]);
const lp = svgParts(logo), cp = svgParts(chev);
const rel = (f) => (f ? path.relative(root, f) : "—");
writeFileSync(path.join(root, "lib/brand-logo.ts"), `// Generated by scripts/brand-logo.mjs from ${[logo, chev, tex].map(rel).join(", ")} — do not edit.
export const KINAN_LOGO: string | null = ${JSON.stringify(uri(logo))};
export const KINAN_LOGO_PATH: string | null = ${JSON.stringify(lp.path)};
export const KINAN_LOGO_VIEWBOX: string | null = ${JSON.stringify(lp.viewBox)};
export const KINAN_CHEVRON_PATH: string | null = ${JSON.stringify(cp.path)};
export const KINAN_CHEVRON_VIEWBOX: string | null = ${JSON.stringify(cp.viewBox)};
export const KINAN_TEXTURE: string | null = ${JSON.stringify(uri(tex))};
`);
const kb = (f) => (f ? `${Math.round(readFileSync(f).length / 1024)} KB` : "none");
console.log(`brand: logo ${rel(logo)} (${kb(logo)}), chevron ${rel(chev)}, texture ${rel(tex)} (${kb(tex)})`);
