// Embeds the Kinan logo (brand/kinan-logo.svg | .png | .webp | .jpg) as a data URI in lib/brand-logo.ts, so the app,
// the single-file demo, the report viewer and the slide player all show it without extra files or network.
// No logo file → KINAN_LOGO = null and the K wordmark is shown instead. Run: npm run brand (also runs before builds).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const TYPES = { svg: "image/svg+xml", png: "image/png", webp: "image/webp", jpg: "image/jpeg", jpeg: "image/jpeg" };
const found = Object.keys(TYPES).map((ext) => path.join(root, "brand", `kinan-logo.${ext}`)).find(existsSync);
const uri = found ? `data:${TYPES[path.extname(found).slice(1)]};base64,${readFileSync(found).toString("base64")}` : null;
writeFileSync(path.join(root, "lib/brand-logo.ts"), `// Generated by scripts/brand-logo.mjs from ${found ? path.relative(root, found) : "(no brand/kinan-logo.* file)"} — do not edit.\nexport const KINAN_LOGO: string | null = ${uri ? JSON.stringify(uri) : "null"};\n`);
console.log(found ? `brand: embedded ${path.relative(root, found)} (${Math.round(readFileSync(found).length / 1024)} KB)` : "brand: no brand/kinan-logo.* — using the K wordmark");
