// Embeds Kinan's brand assets (brand/kinan-logo.svg, kinan-chevron.svg, kinan-texture.jpg) into lib/brand-assets.ts,
// so the app, the single-file HTML, the WhatsApp images and the drawing title blocks all carry the same artwork
// with no runtime file loads. Run: npm run brand (also runs before build).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (f) => { const p = path.join(root, "brand", f); return fs.existsSync(p) ? fs.readFileSync(p) : null; };

function svgPath(buf) {
  if (!buf) return null;
  const s = buf.toString("utf8");
  const vb = /viewBox="([^"]+)"/.exec(s)?.[1];
  const d = /<path[^>]*\sd="([^"]+)"/.exec(s)?.[1];
  return vb && d ? { viewBox: vb, d: d.replace(/\s+/g, " ").trim() } : null;
}
const logo = svgPath(read("kinan-logo.svg"));
const chevron = svgPath(read("kinan-chevron.svg"));
const tex = read("kinan-texture.jpg");
const texture = tex ? `data:image/jpeg;base64,${tex.toString("base64")}` : "";

// Kinan's own typeface (Greta Arabic / Greta Sans from Typotheque, licensed separately): drop the licensed files into
// brand/fonts/ and they are embedded as @font-face under one family name, "Kinan"; the weight and style come from the
// file name (Light, Regular/Book, Medium, SemiBold/Demi, Bold, Black/Heavy; Italic/Oblique). Without them the UI uses
// the stand-ins listed in globals.css (Fira Sans + IBM Plex Sans Arabic from Google Fonts).
const fontDir = path.join(root, "brand", "fonts");
const fontFiles = fs.existsSync(fontDir) ? fs.readdirSync(fontDir).filter((f) => /\.(woff2|woff|ttf|otf)$/i.test(f)).sort() : [];
const weightOf = (n) => /black|heavy|extrabold|ultrabold/i.test(n) ? 800 : /semibold|demibold|demi/i.test(n) ? 600 : /bold/i.test(n) ? 700 : /medium/i.test(n) ? 500 : /light/i.test(n) ? 300 : /thin|hairline/i.test(n) ? 200 : 400;
const faces = fontFiles.map((f) => {
  const ext = f.split(".").pop().toLowerCase(), fmt = { woff2: "woff2", woff: "woff", ttf: "truetype", otf: "opentype" }[ext], mime = { woff2: "font/woff2", woff: "font/woff", ttf: "font/ttf", otf: "font/otf" }[ext];
  const b64 = fs.readFileSync(path.join(fontDir, f)).toString("base64");
  return `@font-face{font-family:"Kinan";font-weight:${weightOf(f)};font-style:${/italic|oblique/i.test(f) ? "italic" : "normal"};font-display:swap;src:url(data:${mime};base64,${b64}) format("${fmt}")}`;
});
fs.writeFileSync(path.join(root, "app", "brand-fonts.css"), `/* Generated by scripts/brand.mjs from brand/fonts/*. ${faces.length ? `${faces.length} face(s) of Kinan's typeface.` : "No brand font files: the stand-in fonts apply."} */\n${faces.join("\n")}\n`);

const out = `// Generated by scripts/brand.mjs from brand/*. Do not edit by hand.
export const LOGO = ${JSON.stringify(logo)} as { viewBox: string; d: string } | null;
export const CHEVRON = ${JSON.stringify(chevron)} as { viewBox: string; d: string } | null;
export const TEXTURE = ${JSON.stringify(texture)};
/** true when Kinan's own typeface files were embedded from brand/fonts/ */
export const BRAND_FONT = ${faces.length > 0};
`;
fs.writeFileSync(path.join(root, "lib", "brand-assets.ts"), out);
console.log(`brand: logo ${logo ? "ok" : "missing"}, chevron ${chevron ? "ok" : "missing"}, texture ${tex ? Math.round(tex.length / 1024) + " KB" : "missing"}, fonts ${faces.length ? faces.length + " face(s) embedded" : "stand-ins (no files in brand/fonts)"}`);
