// Embeds Kinan's brand assets (brand/kinan-logo.svg, kinan-chevron.svg, kinan-texture.jpg) into lib/brand-assets.ts,
// so the app, the single-file HTML, the WhatsApp images and the drawing title blocks all carry the same artwork
// with no runtime file loads. Run: npm run brand (also runs before build).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (f) => { const p = path.join(root, "brand", f); return fs.existsSync(p) ? fs.readFileSync(p) : null; };

function svgPath(buf) {
  if (!buf) return null;
  const s = buf.toString("utf8");
  const vb = /viewBox="([^"]+)"/.exec(s)?.[1];
  const d = /<path[^>]*\sd="([^"]+)"/.exec(s)?.[1];
  return vb && d ? { viewBox: vb, d: d.replace(/\s+/g, " ").trim() } : null;
}
const logo = svgPath(read("kinan-logo.svg"));
const chevron = svgPath(read("kinan-chevron.svg"));
const tex = read("kinan-texture.jpg");
const texture = tex ? `data:image/jpeg;base64,${tex.toString("base64")}` : "";

const out = `// Generated by scripts/brand.mjs from brand/*. Do not edit by hand.
export const LOGO = ${JSON.stringify(logo)} as { viewBox: string; d: string } | null;
export const CHEVRON = ${JSON.stringify(chevron)} as { viewBox: string; d: string } | null;
export const TEXTURE = ${JSON.stringify(texture)};
`;
fs.writeFileSync(path.join(root, "lib", "brand-assets.ts"), out);
console.log(`brand: logo ${logo ? "ok" : "missing"}, chevron ${chevron ? "ok" : "missing"}, texture ${tex ? Math.round(tex.length / 1024) + " KB" : "missing"}`);
